export const labels = {
    en: {
        locale: 'en-us',
        title: 'Gallery',
        language: 'Language',
        logout: 'Logout',
        'general.cancel': 'Cancel',
        'upload-image.title': 'Upload image',
        'upload-image.image-button': 'Drag or click to select image',
        'upload-image.image-required': 'Image is required',
        'upload-image.field-required': 'Field is required.',
        'upload-image.description': 'Description',
        'upload-image.location': 'Location',
        'upload-image.tags': 'Tags',
        'upload-image.date': 'Date',
        'upload-image.upload': 'Upload',
        'upload-image.error': 'Error: Something went wrong',
        'upload-image.success': 'Image uploaded',
        'image-list.upload-image': 'Upload',
        'image-list.add-comment': 'Add a comment',
        'image-list.no-images': 'Looks like there are no images.<br>Click + to upload.',
        'image-list.average-rating': 'Average: ',
        'image-list.location': 'Location: ',
        'image-list.tags': 'Tags: ',
        'image-list.description': 'Description: ',
        'image-list-toolbar.sort-by-location': 'Sort by Location',
        'image-list-toolbar.sort-by-date': 'Sort by Date',
        'image-list-toolbar.filter': 'Search',
        'login.title': 'Login',
        'login.message': 'To login into our app, you need to use your Facebook account',
        'login.button': 'Login with Facebook',
    },
    ro: {
        locale: 'ro-ro',
        title: 'Galerie',
        language: 'Limba',
        logout: 'Ieșire',
        'general.cancel': 'Anulează',
        'upload-image.title': 'Adaugă imagine',
        'upload-image.image-button': 'Trage sau click pentru a selecta imaginea',
        'upload-image.image-required': 'O imagine este necesară',
        'upload-image.field-required': 'Câmp necesar',
        'upload-image.description': 'Descriere',
        'upload-image.location': 'Locație',
        'upload-image.tags': 'Etichete',
        'upload-image.date': 'Data',
        'upload-image.upload': 'Încarcă',
        'upload-image.error': 'Erroare: Încărcarea a fost nereușită',
        'upload-image.success': 'Încărcare completă',
        'image-list.upload-image': 'Încarcă',
        'image-list.add-comment': 'Adaugă comentariu',
        'image-list.no-images': 'Se pare ca nu există nici o imagine.<br>Apasă + pentru a adăuga.',
        'image-list.average-rating': 'Media: ',
        'image-list.location': 'Locație: ',
        'image-list.tags': 'Etichete: ',
        'image-list.description': 'Descriere: ',
        'image-list-toolbar.sort-by-location': 'Ordonează după locație',
        'image-list-toolbar.sort-by-date': 'Ordonează după dată',
        'image-list-toolbar.filter': 'Caută',
        'login.title': 'Logare',
        'login.message': 'Pentru a putea folosi aplicația, trebuie să folosești contul de Facebook',
        'login.button': 'Logare cu Facebook',
    },
    _: {
        en: 'English',
        ro: 'Română',
    }
};