export const labels = {
    en: {
        title: 'Images Demo Application',
        language: 'Language',
        'general.cancel': 'Cancel',
        'upload-image.title': 'Upload image',
        'upload-image.image-button': 'Drag or click to select image',
        'upload-image.image-required': 'Image is required',
        'upload-image.field-required': 'Field is required.',
        'upload-image.description': 'Description',
        'upload-image.location': 'Location',
        'upload-image.tags': 'Tags',
        'upload-image.date': 'Date',
        'upload-image.upload': 'Upload',
        'upload-image.error': 'Error: Something went wrong',
        'upload-image.success': 'Image uploaded',
        'image-list.upload-image': 'Upload',
    },
    ro: {
        title: 'Aplicatie Demo Imagini',
        language: 'Limba',
        'general.cancel': 'Anulează',
        'upload-image.title': 'Adaugă imagine',
        'upload-image.image-button': 'Trage sau click pentru a selecta imaginea',
        'upload-image.image-required': 'O imagine este necesară',
        'upload-image.field-required': 'Câmp necesar',
        'upload-image.description': 'Descriere',
        'upload-image.location': 'Locație',
        'upload-image.tags': 'Etichete',
        'upload-image.date': 'Data',
        'upload-image.upload': 'Încarcă',
        'upload-image.error': 'Erroare: Încărcarea a fost nereușită',
        'upload-image.success': 'Încărcare completă',
        'image-list.upload-image': 'Încarcă',
    },
    _: {
        en: 'English',
        ro: 'Română',
    }
};